export { default as iconEll96 } from '@/assets/pricing/icons/Ellipse 96.svg'
export { default as iconEll97 } from '@/assets/pricing/icons/Ellipse 97.svg'
export { default as iconEll96Alt } from '@/assets/pricing/icons/Ellipse 96 (1).svg'
export { default as iconEll97Alt } from '@/assets/pricing/icons/Ellipse 97 (1).svg'
export { default as iconCheck } from '@/assets/pricing/icons/Frame 2147258648.svg'
export { default as iconHeart } from '@/assets/pricing/icons/idea-heart-svgrepo-com 2.svg'
export { default as iconHeartOnBlue } from '@/assets/pricing/icons/idea-heart-svgrepo-com 2 (1).svg'
export { default as iconFox } from '@/assets/pricing/icons/photo_2026-03-12_15-48-46 1.svg'
export { default as imgBasicBg } from '@/assets/pricing/images/af4cdfe1a0bbc30d8ed3d66855ce3a72e6cc7f02.jpg'
export { default as imgWlBg } from '@/assets/pricing/images/Group 2147258649.svg'
export { default as imgWlFg } from '@/assets/pricing/images/Group 2147258661.svg'
export { default as imgWlFgDark } from '@/assets/pricing/images/Group 2147258661-dark.svg'
