"""add_goal_fields_to_integration

Revision ID: 113e8aa25ef0
Revises: a99fe91b1079
Create Date: 2026-01-13 06:34:26.247358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113e8aa25ef0'
down_revision: Union[str, Sequence[str], None] = 'a99fe91b1079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('selected_goals', sa.String(), nullable=True))
    op.add_column('integrations', sa.Column('primary_goal_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'primary_goal_id')
    op.drop_column('integrations', 'selected_goals')
    # ### end Alembic commands ###
