"""upgrade_metrics_to_bigint_and_add_cascades

Revision ID: 1753da2599ca
Revises: 1910bbe89271
Create Date: 2026-01-10 01:31:12.153288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1753da2599ca'
down_revision: Union[str, Sequence[str], None] = '1910bbe89271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('campaigns_integration_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vk_stats', 'impressions',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('vk_stats', 'clicks',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('vk_stats', 'conversions',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint(op.f('vk_stats_campaign_id_fkey'), 'vk_stats', type_='foreignkey')
    op.drop_constraint(op.f('vk_stats_client_id_fkey'), 'vk_stats', type_='foreignkey')
    op.create_foreign_key(None, 'vk_stats', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vk_stats', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('yandex_groups', 'impressions',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('yandex_groups', 'clicks',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('yandex_groups', 'conversions',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint(op.f('yandex_groups_client_id_fkey'), 'yandex_groups', type_='foreignkey')
    op.create_foreign_key(None, 'yandex_groups', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('yandex_keywords', 'impressions',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('yandex_keywords', 'clicks',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('yandex_keywords', 'conversions',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint(op.f('yandex_keywords_client_id_fkey'), 'yandex_keywords', type_='foreignkey')
    op.create_foreign_key(None, 'yandex_keywords', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('yandex_stats', 'impressions',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('yandex_stats', 'clicks',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('yandex_stats', 'conversions',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint(op.f('yandex_stats_campaign_id_fkey'), 'yandex_stats', type_='foreignkey')
    op.create_foreign_key(None, 'yandex_stats', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yandex_stats', type_='foreignkey')
    op.create_foreign_key(op.f('yandex_stats_campaign_id_fkey'), 'yandex_stats', 'campaigns', ['campaign_id'], ['id'])
    op.alter_column('yandex_stats', 'conversions',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('yandex_stats', 'clicks',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('yandex_stats', 'impressions',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'yandex_keywords', type_='foreignkey')
    op.create_foreign_key(op.f('yandex_keywords_client_id_fkey'), 'yandex_keywords', 'clients', ['client_id'], ['id'])
    op.alter_column('yandex_keywords', 'conversions',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('yandex_keywords', 'clicks',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('yandex_keywords', 'impressions',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'yandex_groups', type_='foreignkey')
    op.create_foreign_key(op.f('yandex_groups_client_id_fkey'), 'yandex_groups', 'clients', ['client_id'], ['id'])
    op.alter_column('yandex_groups', 'conversions',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('yandex_groups', 'clicks',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('yandex_groups', 'impressions',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'vk_stats', type_='foreignkey')
    op.drop_constraint(None, 'vk_stats', type_='foreignkey')
    op.create_foreign_key(op.f('vk_stats_client_id_fkey'), 'vk_stats', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('vk_stats_campaign_id_fkey'), 'vk_stats', 'campaigns', ['campaign_id'], ['id'])
    op.alter_column('vk_stats', 'conversions',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('vk_stats', 'clicks',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('vk_stats', 'impressions',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_integration_id_fkey'), 'campaigns', 'integrations', ['integration_id'], ['id'])
    # ### end Alembic commands ###
