"""add_campaign_model

Revision ID: 1910bbe89271
Revises: a1b2c3d4e5f6
Create Date: 2026-01-09 05:41:32.478695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1910bbe89271'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vk_stats', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'vk_stats', 'campaigns', ['campaign_id'], ['id'])
    op.add_column('yandex_stats', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'yandex_stats', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yandex_stats', type_='foreignkey')
    op.drop_column('yandex_stats', 'campaign_id')
    op.drop_constraint(None, 'vk_stats', type_='foreignkey')
    op.drop_column('vk_stats', 'campaign_id')
    # ### end Alembic commands ###
