"""Initial migration

Revision ID: 95277bcb737d
Revises: 
Create Date: 2025-12-25 02:24:08.880786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95277bcb737d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if userrole enum exists before creating
    from sqlalchemy import text
    connection = op.get_bind()
    result = connection.execute(text("""
        SELECT EXISTS (
            SELECT 1 FROM pg_type WHERE typname = 'userrole'
        )
    """))
    enum_exists = result.scalar()
    
    if not enum_exists:
        op.execute("CREATE TYPE userrole AS ENUM ('ADMIN', 'MANAGER')")
    
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', name='userrole', create_type=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Check if integrationplatform enum exists before creating
    result = connection.execute(text("""
        SELECT EXISTS (
            SELECT 1 FROM pg_type WHERE typname = 'integrationplatform'
        )
    """))
    enum_exists = result.scalar()
    
    if not enum_exists:
        op.execute("CREATE TYPE integrationplatform AS ENUM ('YANDEX_DIRECT', 'VK_ADS', 'YANDEX_METRIKA')")
    
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.Enum('YANDEX_DIRECT', 'VK_ADS', 'YANDEX_METRIKA', name='integrationplatform', create_type=False), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrika_goals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('goal_name', sa.String(), nullable=True),
    sa.Column('conversion_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrika_goals_date'), 'metrika_goals', ['date'], unique=False)
    op.create_table('vk_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_stats_date'), 'vk_stats', ['date'], unique=False)
    op.create_table('yandex_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yandex_stats_date'), 'yandex_stats', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yandex_stats_date'), table_name='yandex_stats')
    op.drop_table('yandex_stats')
    op.drop_index(op.f('ix_vk_stats_date'), table_name='vk_stats')
    op.drop_table('vk_stats')
    op.drop_index(op.f('ix_metrika_goals_date'), table_name='metrika_goals')
    op.drop_table('metrika_goals')
    op.drop_table('integrations')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
