"""Add VK credentials to Integration

Revision ID: e3b4acdd7635
Revises: 314d27135fdd
Create Date: 2025-12-29 13:36:56.973684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b4acdd7635'
down_revision: Union[str, Sequence[str], None] = '314d27135fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('platform_client_id', sa.String(), nullable=True))
    op.add_column('integrations', sa.Column('platform_client_secret', sa.String(), nullable=True))
    op.create_index(op.f('ix_integrations_client_id'), 'integrations', ['client_id'], unique=False)
    op.create_index(op.f('ix_vk_stats_client_id'), 'vk_stats', ['client_id'], unique=False)
    op.create_index(op.f('ix_yandex_keywords_client_id'), 'yandex_keywords', ['client_id'], unique=False)
    op.create_index(op.f('ix_yandex_stats_client_id'), 'yandex_stats', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yandex_stats_client_id'), table_name='yandex_stats')
    op.drop_index(op.f('ix_yandex_keywords_client_id'), table_name='yandex_keywords')
    op.drop_index(op.f('ix_vk_stats_client_id'), table_name='vk_stats')
    op.drop_index(op.f('ix_integrations_client_id'), table_name='integrations')
    op.drop_column('integrations', 'platform_client_secret')
    op.drop_column('integrations', 'platform_client_id')
    # ### end Alembic commands ###
